const http = require("http");
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const QRCode = require("qrcode");

const VOLUME_DIR = process.env.CONFIG_DIR || "/config";
const CONFIG_DIR = path.join(VOLUME_DIR, ".hermes");
const WEB_CONTAINER = process.env.WEB_CONTAINER || "zot24-hermes_web_1";
const PORT = parseInt(process.env.SETUP_PORT || "8080");
const SETUP_SENTINEL = path.join(VOLUME_DIR, ".setup-complete");
const ENV_FILE = path.join(CONFIG_DIR, ".env");
const CONFIG_FILE = path.join(CONFIG_DIR, "config.yaml");
const STATE_FILE = path.join(CONFIG_DIR, "gateway_state.json");

// Pre-load static files
const WIZARD_HTML = fs.readFileSync(path.join(__dirname, "wizard.html"), "utf8");
const STATUS_HTML = fs.readFileSync(path.join(__dirname, "status.html"), "utf8");

// ── Helpers ──────────────────────────────────────────────────────────────────

function isConfigured() {
  return fs.existsSync(SETUP_SENTINEL);
}

function ensureConfigDir() {
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }
}

function readGatewayState() {
  try {
    if (fs.existsSync(STATE_FILE)) {
      return JSON.parse(fs.readFileSync(STATE_FILE, "utf8"));
    }
  } catch (e) {
    console.error("Error reading gateway state:", e.message);
  }
  return null;
}

function readCurrentConfig() {
  const config = {};
  try {
    if (fs.existsSync(ENV_FILE)) {
      const content = fs.readFileSync(ENV_FILE, "utf8");
      content.split("\n").forEach((line) => {
        const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
        if (match) {
          config[match[1]] = match[2];
        }
      });
    }
  } catch (e) {
    console.error("Error reading config:", e.message);
  }
  return config;
}

function maskSecret(value) {
  if (!value || value.length < 8) return "****";
  return value.slice(0, 4) + "****" + value.slice(-4);
}

function writeEnvFile(config) {
  const lines = [
    "# Hermes Agent Configuration",
    "# Generated by hermes-umbrel setup wizard",
    "",
  ];

  for (const [key, value] of Object.entries(config)) {
    if (value !== undefined && value !== null && value !== "") {
      lines.push(`${key}=${value}`);
    }
  }

  fs.writeFileSync(ENV_FILE, lines.join("\n") + "\n", { mode: 0o600 });
}

function writeConfigYaml(config) {
  const model = config.HERMES_MODEL || "anthropic/claude-sonnet-4-20250514";
  const provider = config.HERMES_PROVIDER || "auto";

  let platforms = "";

  if (config.TELEGRAM_BOT_TOKEN) {
    platforms += `
    telegram:
      enabled: true`;
    if (config.TELEGRAM_HOME_CHAT_ID) {
      platforms += `
      home_channel: "${config.TELEGRAM_HOME_CHAT_ID}"`;
    }
  }

  if (config.WHATSAPP_ENABLED === "true") {
    platforms += `
    whatsapp:
      enabled: true`;
  }

  const yaml = `# Hermes Agent Configuration
# Generated by hermes-umbrel setup wizard

model:
  default: "${model}"
  provider: "${provider}"

gateway:
  streaming: true
  platforms:${platforms || "\n    # No platforms configured"}

session_reset:
  mode: both
  at_hour: 4
  idle_minutes: 1440

update:
  checkOnStart: false

context_compression:
  enabled: true

memory:
  enabled: true
`;

  fs.writeFileSync(CONFIG_FILE, yaml, { mode: 0o600 });
}

function restartWebContainer() {
  try {
    const socketPath = "/var/run/docker.sock";
    if (!fs.existsSync(socketPath)) {
      console.error("Docker socket not available");
      return false;
    }

    // Use curl to talk to Docker socket
    execSync(
      `curl -s --unix-socket ${socketPath} -X POST "http://localhost/containers/${WEB_CONTAINER}/restart?t=10"`,
      { timeout: 30000 }
    );
    console.log(`Restarted container: ${WEB_CONTAINER}`);
    return true;
  } catch (e) {
    console.error("Failed to restart web container:", e.message);
    return false;
  }
}

// ── Telegram API helpers ─────────────────────────────────────────────────────

async function telegramGetMe(token) {
  const resp = await fetch(`https://api.telegram.org/bot${token}/getMe`);
  return resp.json();
}

async function telegramSendMessage(token, chatId, text) {
  const resp = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: chatId, text }),
  });
  return resp.json();
}

// ── Request body parser ──────────────────────────────────────────────────────

function parseBody(req) {
  return new Promise((resolve, reject) => {
    let body = "";
    req.on("data", (chunk) => {
      body += chunk;
      if (body.length > 1e6) {
        req.destroy();
        reject(new Error("Body too large"));
      }
    });
    req.on("end", () => {
      try {
        resolve(JSON.parse(body));
      } catch {
        reject(new Error("Invalid JSON"));
      }
    });
    req.on("error", reject);
  });
}

// ── Route handlers ───────────────────────────────────────────────────────────

function sendJson(res, statusCode, data) {
  res.writeHead(statusCode, { "Content-Type": "application/json" });
  res.end(JSON.stringify(data));
}

function sendHtml(res, html) {
  res.writeHead(200, {
    "Content-Type": "text/html",
    "Cache-Control": "no-store",
  });
  res.end(html);
}

async function handleRequest(req, res) {
  const url = new URL(req.url, `http://${req.headers.host}`);

  // ── Static pages ──
  if (req.method === "GET" && url.pathname === "/") {
    sendHtml(res, isConfigured() ? STATUS_HTML : WIZARD_HTML);
    return;
  }

  if (req.method === "GET" && url.pathname === "/setup") {
    sendHtml(res, WIZARD_HTML);
    return;
  }

  // ── API: Get current config (masked) ──
  if (req.method === "GET" && url.pathname === "/api/setup") {
    const config = readCurrentConfig();
    const masked = {};
    for (const [key, value] of Object.entries(config)) {
      masked[key] = key.includes("KEY") || key.includes("TOKEN") || key.includes("SECRET")
        ? maskSecret(value)
        : value;
    }
    sendJson(res, 200, { configured: isConfigured(), config: masked });
    return;
  }

  // ── API: Save setup ──
  if (req.method === "POST" && url.pathname === "/api/setup") {
    try {
      const data = await parseBody(req);

      // Validate: need at least one LLM key
      const hasLlmKey = data.OPENROUTER_API_KEY || data.ANTHROPIC_API_KEY ||
                        data.OLLAMA_BASE_URL || data.GLM_API_KEY ||
                        data.KIMI_API_KEY || data.MINIMAX_API_KEY ||
                        data.MINIMAX_CN_API_KEY || data.DEEPSEEK_API_KEY ||
                        data.DASHSCOPE_API_KEY || data.OPENCODE_ZEN_API_KEY ||
                        data.OPENCODE_GO_API_KEY;
      if (!hasLlmKey) {
        sendJson(res, 400, { error: "At least one LLM provider API key is required" });
        return;
      }

      // Validate: need at least one platform
      const hasPlatform = data.TELEGRAM_BOT_TOKEN || data.WHATSAPP_ENABLED === "true";
      if (!hasPlatform) {
        sendJson(res, 400, { error: "At least one messaging platform must be configured" });
        return;
      }

      ensureConfigDir();

      // Build the env config
      const envConfig = {};
      const envKeys = [
        "OPENROUTER_API_KEY", "ANTHROPIC_API_KEY",
        "GLM_API_KEY", "KIMI_API_KEY", "MINIMAX_API_KEY", "MINIMAX_CN_API_KEY",
        "DEEPSEEK_API_KEY", "DASHSCOPE_API_KEY",
        "OPENCODE_ZEN_API_KEY", "OPENCODE_GO_API_KEY",
        "OLLAMA_BASE_URL", "HERMES_MODEL", "HERMES_PROVIDER",
        "TELEGRAM_BOT_TOKEN", "TELEGRAM_HOME_CHAT_ID",
        "WHATSAPP_ENABLED", "WHATSAPP_ALLOWED_USERS",
        "DISCORD_BOT_TOKEN", "SLACK_BOT_TOKEN", "SLACK_APP_TOKEN",
      ];

      for (const key of envKeys) {
        if (data[key]) {
          envConfig[key] = data[key];
        }
      }

      // Set HERMES_REGEN_CONFIG to force config regeneration
      envConfig.HERMES_REGEN_CONFIG = "true";

      writeEnvFile(envConfig);
      writeConfigYaml(envConfig);

      // Mark as configured
      fs.writeFileSync(SETUP_SENTINEL, new Date().toISOString(), { mode: 0o644 });

      // Restart the web container
      const restarted = restartWebContainer();

      sendJson(res, 200, {
        success: true,
        restarted,
        message: restarted
          ? "Configuration saved. Gateway is restarting..."
          : "Configuration saved. Please restart the app manually.",
      });
    } catch (e) {
      console.error("Setup error:", e);
      sendJson(res, 500, { error: e.message });
    }
    return;
  }

  // ── API: Test Telegram ──
  if (req.method === "POST" && url.pathname === "/api/test-telegram") {
    try {
      const data = await parseBody(req);
      const { token, chatId } = data;

      if (!token || !chatId) {
        sendJson(res, 400, { error: "Bot token and chat ID are required" });
        return;
      }

      // First verify the token
      const me = await telegramGetMe(token);
      if (!me.ok) {
        sendJson(res, 400, {
          error: `Invalid bot token: ${me.description || "unknown error"}`,
        });
        return;
      }

      // Send test message
      const result = await telegramSendMessage(
        token,
        chatId,
        `Hermes is connected! Your AI agent is ready to chat.\n\nBot: @${me.result.username}`
      );

      if (!result.ok) {
        sendJson(res, 400, {
          error: `Failed to send message: ${result.description || "unknown error"}. Make sure you've started a chat with the bot and the chat ID is correct.`,
        });
        return;
      }

      sendJson(res, 200, {
        success: true,
        botName: me.result.first_name,
        botUsername: me.result.username,
      });
    } catch (e) {
      sendJson(res, 500, { error: e.message });
    }
    return;
  }

  // ── API: WhatsApp QR code ──
  // The bridge writes the raw QR string to whatsapp/qr.txt on the shared volume.
  // Once paired, it deletes the file. The status page polls this endpoint.
  // Returns a data URL (base64 PNG) so no client-side QR library is needed.
  if (req.method === "GET" && url.pathname === "/api/whatsapp-qr") {
    const qrFile = path.join(CONFIG_DIR, "whatsapp", "qr.txt");
    const sessionFile = path.join(CONFIG_DIR, "whatsapp", "session", "creds.json");
    const paired = fs.existsSync(sessionFile);

    if (paired) {
      sendJson(res, 200, { status: "paired", qrImage: null });
      return;
    }

    try {
      if (fs.existsSync(qrFile)) {
        const qr = fs.readFileSync(qrFile, "utf8").trim();
        const dataUrl = await QRCode.toDataURL(qr, {
          width: 280,
          margin: 2,
          color: { dark: "#000000", light: "#ffffff" },
        });
        sendJson(res, 200, { status: "pending", qrImage: dataUrl });
      } else {
        sendJson(res, 200, { status: "waiting", qrImage: null, message: "Waiting for WhatsApp bridge to generate QR code..." });
      }
    } catch (e) {
      console.error("QR generation error:", e.message);
      sendJson(res, 200, { status: "waiting", qrImage: null, message: "Waiting for QR code..." });
    }
    return;
  }

  // ── API: Gateway status ──
  if (req.method === "GET" && url.pathname === "/api/status") {
    const state = readGatewayState();
    const config = readCurrentConfig();

    const platforms = [];
    if (config.TELEGRAM_BOT_TOKEN) {
      platforms.push({ name: "Telegram", enabled: true });
    }
    if (config.WHATSAPP_ENABLED === "true") {
      const whatsappAuth = path.join(CONFIG_DIR, "whatsapp", "session", "creds.json");
      const qrFile = path.join(CONFIG_DIR, "whatsapp", "qr.txt");
      platforms.push({
        name: "WhatsApp",
        enabled: true,
        paired: fs.existsSync(whatsappAuth),
        hasQr: fs.existsSync(qrFile),
      });
    }
    if (config.DISCORD_BOT_TOKEN) {
      platforms.push({ name: "Discord", enabled: true });
    }
    if (config.SLACK_BOT_TOKEN) {
      platforms.push({ name: "Slack", enabled: true });
    }

    sendJson(res, 200, {
      configured: isConfigured(),
      gateway: state,
      platforms,
      model: config.HERMES_MODEL || "anthropic/claude-sonnet-4-20250514",
      provider: config.HERMES_PROVIDER || "auto",
    });
    return;
  }

  // ── API: Health check ──
  if (req.method === "GET" && url.pathname === "/api/health") {
    sendJson(res, 200, { ok: true, configured: isConfigured() });
    return;
  }

  // ── API: Restart gateway ──
  if (req.method === "POST" && url.pathname === "/api/restart") {
    const restarted = restartWebContainer();
    sendJson(res, 200, { success: restarted });
    return;
  }

  // ── API: List pending pairing requests ──
  if (req.method === "GET" && url.pathname === "/api/pairing") {
    const pairingDir = path.join(CONFIG_DIR, "pairing");
    const results = [];
    try {
      if (fs.existsSync(pairingDir)) {
        const files = fs.readdirSync(pairingDir).filter(f => f.endsWith("-pending.json"));
        for (const file of files) {
          const platform = file.replace("-pending.json", "");
          const pending = JSON.parse(fs.readFileSync(path.join(pairingDir, file), "utf8"));
          const now = Date.now() / 1000;
          for (const [code, info] of Object.entries(pending)) {
            // Skip expired codes (1 hour TTL)
            if (now - info.created_at > 3600) continue;
            results.push({
              platform,
              code,
              user_id: info.user_id,
              user_name: info.user_name || "",
              age_minutes: Math.floor((now - info.created_at) / 60),
            });
          }
        }
      }
    } catch (e) {
      console.error("Error reading pairing data:", e.message);
    }
    sendJson(res, 200, { pending: results });
    return;
  }

  // ── API: Approve a pairing code ──
  if (req.method === "POST" && url.pathname === "/api/pairing/approve") {
    try {
      const data = await parseBody(req);
      const { platform, code } = data;
      if (!platform || !code) {
        sendJson(res, 400, { error: "Platform and code are required" });
        return;
      }

      const pairingDir = path.join(CONFIG_DIR, "pairing");
      const pendingFile = path.join(pairingDir, `${platform}-pending.json`);
      const approvedFile = path.join(pairingDir, `${platform}-approved.json`);

      if (!fs.existsSync(pendingFile)) {
        sendJson(res, 404, { error: "No pending requests for this platform" });
        return;
      }

      const pending = JSON.parse(fs.readFileSync(pendingFile, "utf8"));
      const upperCode = code.toUpperCase().trim();

      if (!pending[upperCode]) {
        sendJson(res, 404, { error: "Code not found or expired" });
        return;
      }

      const entry = pending[upperCode];
      delete pending[upperCode];
      fs.writeFileSync(pendingFile, JSON.stringify(pending, null, 2), { mode: 0o600 });

      // Add to approved list
      let approved = {};
      try {
        if (fs.existsSync(approvedFile)) {
          approved = JSON.parse(fs.readFileSync(approvedFile, "utf8"));
        }
      } catch (e) {}

      approved[entry.user_id] = {
        user_name: entry.user_name || "",
        approved_at: Date.now() / 1000,
        approved_via: "umbrel-ui",
      };
      fs.writeFileSync(approvedFile, JSON.stringify(approved, null, 2), { mode: 0o600 });

      // Send confirmation message to the user via the gateway's bridge
      try {
        const webHost = process.env.WEB_CONTAINER || "zot24-hermes_web_1";
        // WhatsApp bridge runs on port 3000 inside the web container
        if (data.platform === "whatsapp") {
          await fetch(`http://${webHost}:3000/send`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              chatId: entry.user_id,
              message: `You're approved! Welcome to Hermes Agent. You can now chat with me anytime.`,
            }),
          }).catch(() => {});
        }
        // Telegram: use Bot API directly
        if (data.platform === "telegram") {
          const tgToken = readCurrentConfig().TELEGRAM_BOT_TOKEN;
          if (tgToken) {
            await fetch(`https://api.telegram.org/bot${tgToken}/sendMessage`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                chat_id: entry.user_id,
                text: `You're approved! Welcome to Hermes Agent. You can now chat with me anytime.`,
              }),
            }).catch(() => {});
          }
        }
      } catch (e) {
        console.error("Failed to send approval message:", e.message);
      }

      sendJson(res, 200, {
        success: true,
        user_id: entry.user_id,
        user_name: entry.user_name || "",
      });
    } catch (e) {
      sendJson(res, 500, { error: e.message });
    }
    return;
  }

  // ── 404 ──
  res.writeHead(404, { "Content-Type": "text/plain" });
  res.end("Not Found");
}

// ── Server ───────────────────────────────────────────────────────────────────

const server = http.createServer((req, res) => {
  handleRequest(req, res).catch((err) => {
    console.error("Request error:", err);
    if (!res.headersSent) {
      sendJson(res, 500, { error: "Internal server error" });
    }
  });
});

ensureConfigDir();

server.listen(PORT, "0.0.0.0", () => {
  console.log(`Hermes setup server listening on port ${PORT}`);
  console.log(`Configured: ${isConfigured()}`);
});

process.on("SIGTERM", () => {
  console.log("Received SIGTERM, shutting down...");
  server.close();
  process.exit(0);
});
