#!/bin/bash
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-/home/hermes/.hermes}"
SKELETON_DIR="/home-skeleton"
HERMES_USER="hermes"
HERMES_UID=1000

# ── Phase 1: Run as root — fix permissions, then re-exec as hermes ───────────
if [ "$(id -u)" = "0" ]; then
    echo "=== Hermes Agent Entrypoint (root phase) ==="

    # Ensure home directory exists
    mkdir -p /home/hermes
    chown "$HERMES_UID:$HERMES_UID" /home/hermes

    # Ensure HERMES_HOME exists and is owned by hermes
    mkdir -p "$HERMES_HOME"
    chown -R "$HERMES_UID:$HERMES_UID" "$HERMES_HOME"

    # Fix linuxbrew volume ownership
    chown -R "$HERMES_UID:$HERMES_UID" /home/linuxbrew 2>/dev/null || true

    echo "Permissions fixed, re-executing as $HERMES_USER..."
    exec su -s /bin/bash "$HERMES_USER" -- "$0" "$@"
fi

# ── Phase 2: Run as hermes user ──────────────────────────────────────────────
echo "=== Hermes Agent Entrypoint (user phase) ==="
echo "HERMES_HOME: $HERMES_HOME"

# ── Initialize home directory from skeleton (first run) ──────────────────────
if [ -d "$SKELETON_DIR" ]; then
    for item in "$SKELETON_DIR"/* "$SKELETON_DIR"/.*; do
        basename=$(basename "$item")
        [ "$basename" = "." ] || [ "$basename" = ".." ] && continue
        [ ! -e "$item" ] && continue
        # linuxbrew is mounted as a separate volume at /home/linuxbrew
        [ "$basename" = "linuxbrew" ] && continue

        dest="$HOME/$basename"
        if [ ! -e "$dest" ]; then
            echo "Copying $basename to home..."
            cp -r "$item" "$dest"
        fi
    done
    echo "Home directory initialized"
fi

# Initialize linuxbrew volume if empty (separate mount point)
if [ -d "$SKELETON_DIR/linuxbrew" ] && [ ! -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
    echo "Initializing linuxbrew volume..."
    cp -r "$SKELETON_DIR/linuxbrew/." /home/linuxbrew/
    echo "Linuxbrew initialized"
fi

# ── Create required directories ──────────────────────────────────────────────
mkdir -p "$HERMES_HOME"/{sessions,logs,pairing,hooks,image_cache,audio_cache,memories,skills,whatsapp,cron}

# ── Source environment from setup server config ──────────────────────────────
if [ -f "$HERMES_HOME/.env" ]; then
    echo "Loading environment from $HERMES_HOME/.env"
    set -a
    # shellcheck disable=SC1091
    source "$HERMES_HOME/.env"
    set +a
fi

if [ -f "$HERMES_HOME/.env.local" ]; then
    set -a
    # shellcheck disable=SC1091
    source "$HERMES_HOME/.env.local"
    set +a
fi

# ── Generate config.yaml if needed ───────────────────────────────────────────
config_file="$HERMES_HOME/config.yaml"

if [ ! -f "$config_file" ] || [ "${HERMES_REGEN_CONFIG:-}" = "true" ]; then
    echo "Generating config.yaml..."

    model="${HERMES_MODEL:-anthropic/claude-sonnet-4-20250514}"
    provider="${HERMES_PROVIDER:-auto}"

    # Build gateway platforms section
    platforms=""

    if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
        platforms="${platforms}
    telegram:
      enabled: true"
        if [ -n "${TELEGRAM_HOME_CHAT_ID:-}" ]; then
            platforms="${platforms}
      home_channel: \"${TELEGRAM_HOME_CHAT_ID}\""
        fi
    fi

    if [ "${WHATSAPP_ENABLED:-false}" = "true" ]; then
        platforms="${platforms}
    whatsapp:
      enabled: true"
    fi

    if [ -n "${DISCORD_BOT_TOKEN:-}" ]; then
        platforms="${platforms}
    discord:
      enabled: true"
    fi

    if [ -n "${SLACK_BOT_TOKEN:-}" ]; then
        platforms="${platforms}
    slack:
      enabled: true"
    fi

    cat > "$config_file" <<YAML
# Hermes Agent Configuration
# Generated by hermes-umbrel entrypoint

model:
  default: "${model}"
  provider: "${provider}"

gateway:
  streaming: true
  platforms:${platforms:-"
    # No platforms configured"}

session_reset:
  mode: both
  at_hour: 4
  idle_minutes: 1440

update:
  checkOnStart: false

context_compression:
  enabled: true

memory:
  enabled: true
YAML

    chmod 600 "$config_file"
    echo "Config generated at $config_file"
else
    echo "Config exists at $config_file, using existing"
fi

# ── Activate venv and start ──────────────────────────────────────────────────
# shellcheck disable=SC1091
source /app/venv/bin/activate

case "${1:-gateway}" in
    gateway)
        echo "Starting Hermes gateway..."
        # Use 'run' (foreground) not 'start' (systemctl) — no systemd in Docker
        exec hermes gateway run
        ;;
    shell)
        echo "Starting shell..."
        exec /bin/bash
        ;;
    *)
        exec "$@"
        ;;
esac
