#!/bin/bash
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-/home/hermes/.hermes}"
SKELETON_DIR="/home-skeleton"

# ── Initialize home directory from skeleton (first run) ──────────────────────
init_home() {
    local home_dir="${HOME:-/home/hermes}"

    if [ -d "$SKELETON_DIR" ]; then
        for item in "$SKELETON_DIR"/*  "$SKELETON_DIR"/.*; do
            local basename
            basename=$(basename "$item")
            [ "$basename" = "." ] || [ "$basename" = ".." ] && continue
            [ ! -e "$item" ] && continue

            local dest="$home_dir/$basename"
            if [ ! -e "$dest" ]; then
                echo "Copying $basename to home..."
                cp -r "$item" "$dest"
            fi
        done
        echo "Home directory initialized"
    fi
}

# ── Create required directories ──────────────────────────────────────────────
init_dirs() {
    mkdir -p "$HERMES_HOME"/{sessions,logs,pairing,hooks,image_cache,audio_cache,memories,skills,whatsapp,cron}
}

# ── Source environment from setup server config ──────────────────────────────
load_env() {
    if [ -f "$HERMES_HOME/.env" ]; then
        echo "Loading environment from $HERMES_HOME/.env"
        set -a
        # shellcheck disable=SC1091
        source "$HERMES_HOME/.env"
        set +a
    fi

    if [ -f "$HERMES_HOME/.env.local" ]; then
        set -a
        # shellcheck disable=SC1091
        source "$HERMES_HOME/.env.local"
        set +a
    fi
}

# ── Generate config.yaml if it doesn't exist ─────────────────────────────────
# The setup server writes hermes.env with all the user's settings.
# This function reads those env vars and generates a minimal config.yaml
# that hermes gateway can consume.
generate_config() {
    local config_file="$HERMES_HOME/config.yaml"

    # Don't overwrite existing config unless HERMES_REGEN_CONFIG is set
    if [ -f "$config_file" ] && [ "${HERMES_REGEN_CONFIG:-}" != "true" ]; then
        echo "Config exists at $config_file, using existing"
        return
    fi

    echo "Generating config.yaml..."

    local model="${HERMES_MODEL:-anthropic/claude-sonnet-4-20250514}"
    local provider="${HERMES_PROVIDER:-auto}"

    # Build gateway platforms section
    local platforms=""

    if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
        platforms="${platforms}
    telegram:
      enabled: true"
        if [ -n "${TELEGRAM_HOME_CHAT_ID:-}" ]; then
            platforms="${platforms}
      home_channel: \"${TELEGRAM_HOME_CHAT_ID}\""
        fi
    fi

    if [ "${WHATSAPP_ENABLED:-false}" = "true" ]; then
        platforms="${platforms}
    whatsapp:
      enabled: true"
    fi

    if [ -n "${DISCORD_BOT_TOKEN:-}" ]; then
        platforms="${platforms}
    discord:
      enabled: true"
    fi

    if [ -n "${SLACK_BOT_TOKEN:-}" ]; then
        platforms="${platforms}
    slack:
      enabled: true"
    fi

    cat > "$config_file" <<YAML
# Hermes Agent Configuration
# Generated by hermes-umbrel entrypoint

model:
  default: "${model}"
  provider: "${provider}"

gateway:
  streaming: true
  platforms:${platforms:-"
    # No platforms configured"}

session_reset:
  mode: both
  at_hour: 4
  idle_minutes: 1440

update:
  checkOnStart: false

context_compression:
  enabled: true

memory:
  enabled: true
YAML

    chmod 600 "$config_file"
    echo "Config generated at $config_file"
}

# ── Main ─────────────────────────────────────────────────────────────────────

echo "=== Hermes Agent Entrypoint ==="
echo "HERMES_HOME: $HERMES_HOME"

init_home
init_dirs
load_env
generate_config

# Activate the virtual environment
# shellcheck disable=SC1091
source /app/venv/bin/activate

case "${1:-gateway}" in
    gateway)
        echo "Starting Hermes gateway..."
        exec hermes gateway start
        ;;
    shell)
        echo "Starting shell..."
        exec /bin/bash
        ;;
    *)
        exec "$@"
        ;;
esac
