services:
  web:
    image: caronc/apprise:latest
    ports:
      - "8000:8000"
    environment:
      TZ: America/Asuncion
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: "1"
      APPRISE_ADMIN: "yes"
    volumes:
      - ./data/config:/config
      - ./data/plugin:/plugin
      - ./data/attach:/attach

  ingest:
    image: caronc/apprise:latest
    ports:
      - "8080:8080"
    command: ["python", "/opt/apprise/ntfy_ingest.py"]
    environment:
      TZ: America/Asuncion
      APPRISE_URL: http://web:8000
      DEFAULT_KEY: notify
      LISTEN_PORT: "8080"
    volumes:
      - ./ntfy_ingest.py:/opt/apprise/ntfy_ingest.py:ro
    depends_on:
      - web
